name: API Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven and run tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()  # Runs even if tests fail
        run: mvn allure:report
             mv allure-report/index.html allure-report/allure-report.html
      - name: Upload Allure Report
        if: always()  # Runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
              name: "allure-report"
              path: "allure-report/allure-report.html"
